Muffintechxyz/metaplex

js/packages/web/src/components-v2/sections/ExploreCollections/ExploreCollections.tsx, js/packages/web/src/hooks/useSearch.ts
FN-Collection Inner Search.
Ticket: https://muffintech.atlassian.net/browse/KARMAVERSE-56
- Implemented marketplace search function.
=> KARMAVERSE-56

js/packages/web/src/components/Layout/index.tsx, js/packages/web/src/ui/sections/Header/Header.tsx
-Integrated global search with the new header.
=> KARMAVERSE-39

js/packages/web/src/ui/sections/HottestAuctions/HottestAuctions.tsx, js/packages/web/src/views/home/components/SalesList/hooks/useAuctionsList/index.ts
Added my live auctions tab.
https://muffintech.atlassian.net/browse/KARMAVERSE-60
=> KARMAVERSE-60

js/packages/common/src/molecules/BidCard/BidCard.tsx, js/packages/web/src/components-v2/views/Collection/Collection.tsx, js/packages/web/src/hooks/useNFTData.tsx, js/packages/web/src/ui/sections/Hero/Hero.tsx, js/packages/web/src/ui/sections/Hero/LiveNFTCard.tsx, js/packages/web/src/ui/sections/HottestAuctions/AuctionsCard.tsx
Main banner with live data. 
- Added NFT minted count.
- Added artist count.
- Daily SOL volume **not added**
- Main images creator profile **image nod added**
- Created customer hook to get NFT data.
https://muffintech.atlassian.net/browse/KARMAVERSE-24
=> Karmaverse 24

js/packages/common/src/actions/metadata.ts, js/packages/web/.env, js/packages/web/src/api/index.ts, js/packages/web/src/api/tagApi.ts, js/packages/web/src/views/artCreate/index.tsx
- Implement tags when create new NFT.
- Integrate create tags for NFT API with addArt
=> Tags for NFTs

js/packages/web/src/views/artCreate/index.tsx
- Fix the quantity change issue
- Fix the add attributes for NFT issue
=> Bug fixes for create art page

js/packages/common/src/molecules/AttributesCard/AttributesCard.tsx, js/packages/web/src/hooks/useArt.ts, js/packages/web/src/ui/sections/CollectionAppliedFilters/CollectionAppliedFilters.tsx, js/packages/web/src/ui/sections/CollectionNftList/NFTCardWrapper.tsx, js/packages/web/src/ui/sections/CollectionSidebar/CollectionSidebar.tsx, js/packages/web/src/ui/views/Collection/Collection.tsx
Make attribute array related to the collection.
Add feature to attribute selection.
=> Attributes filters. 

js/packages/web/src/ui/sections/CollectionActionsBar/CollectionActionsBar.tsx, js/packages/web/src/ui/sections/RecentCollections/RecentCollections.tsx, js/packages/web/src/ui/sections/TrendingCollections/TrendingCollections.tsx, js/packages/web/src/ui/views/Collection/Collection.tsx, js/packages/web/src/ui/views/Home/Home.tsx
Implement filters.
1. Filter by attribute.
2. Filter by price.
3. Filter by search text.
=> Karmaverse-51

js/packages/web/src/components-v2/sections/ExploreCollections/ExploreCollections.tsx, js/packages/web/src/hooks/useCollections.ts, js/packages/web/src/hooks/useSearch.ts, js/packages/web/src/ui/sections/CollectionActionsBar/CollectionActionsBar.tsx, js/packages/web/src/ui/sections/RecentCollections/CollectionCard.tsx, js/packages/web/src/ui/sections/RecentCollections/RecentCollections.tsx, js/packages/web/src/ui/sections/TrendingCollections/TrendingCollections.tsx, js/packages/web/src/ui/views/Collection/Collection.tsx, js/packages/web/src/ui/views/Discover/Discover.tsx, js/packages/web/src/ui/views/Home/Home.tsx
Discover collections page data binding.
- Bind all data to the collection page.
- Implement global search.
- Implement search in collection page.
- Implement pagination.
=> KARMAVERSE-52

js/packages/common/src/atoms/Avatar/Avatar.tsx, js/packages/web/src/components/AuctionCard/index.tsx, js/packages/web/src/ui/sections/HottestAuctions/HottestAuctions.tsx, js/packages/web/src/ui/sections/NFTDetailsBody/NFTDetailsBody.tsx, js/packages/web/src/ui/sections/NFTDetailsInfo/NFTDetailsInfo.tsx, js/packages/web/src/ui/sections/NFTDetailsTabs/NFTDetailsTabs.tsx, js/packages/web/src/ui/sections/NFTDetailsTopBar/NFTDetailsTopBar.tsx, js/packages/web/src/ui/views/Collection/Collection.tsx, js/packages/web/src/ui/views/NFTDetails/NFTDetails.tsx, js/packages/web/src/views/auction/index.tsx
=> KARMAVERSE-69

js/packages/web/src/api/index.ts, js/packages/web/src/api/salesHistoryApi.ts, js/packages/web/src/components/AuctionCard/index.tsx, js/packages/web/src/ui/sections/NFTDetailsActivity/NFTDetailsActivity.tsx, js/packages/web/src/ui/sections/NFTDetailsTabs/NFTDetailsTabs.tsx, js/packages/web/src/views/artCreate/index.tsx
- Develop new API endpoint to create sales record for each `Quick Buy` transaction
- Develop get API endpoint to fetch previous transaction details for selected NFT mint key
- Modify the `NFTDetailsActivity` component to display the previous transaction details
=> KARMAVERSE-63 - FN-Statistics

js/packages/web/src/hooks/useCollections.ts, js/packages/web/src/ui/sections/NFTDetailsBody/NFTDetailsBody.tsx, js/packages/web/src/ui/sections/RecentCollections/CollectionCard.tsx
Listening to a Collection minted in outside Karmaplex.
Implemented only the discover collections page. 
https://muffintech.atlassian.net/browse/KARMAVERSE-72
=> KARMAVERSE-72

js/packages/web/src/components/AuctionCard/index.tsx, js/packages/web/src/ui/views/NFTDetails/NFTDetails.tsx
=> NFT-Detail-Page

js/packages/web/src/components/AuctionCard/hooks/useActionButtonContent.ts, js/packages/web/src/components/AuctionCard/index.tsx, js/packages/web/src/ui/sections/NFTDetailsBody/NFTDetailsBody.tsx
=> Detail page bug fixed

js/packages/web/src/ui/sections/NFTDetailsInfo/NFTDetailsInfo.tsx, js/packages/web/src/views/artCreate/index.tsx
Add NFT information under `Details` tab
=> KARMAVERSE 63 - FN-Statistics - NFT `Details` tab

js/packages/web/src/hooks/useCollections.ts, js/packages/web/src/ui/sections/BlockCarousel/BlockCarousel.tsx, js/packages/web/src/ui/sections/BlockCarousel/Carousel.tsx, js/packages/web/src/ui/sections/HottestAuctions/HottestAuctions.tsx, js/packages/web/src/ui/sections/RecentCollections/CollectionCard.tsx, js/packages/web/src/ui/sections/RecentCollections/RecentCollections.tsx, js/packages/web/src/ui/sections/TrendingCollections/TrendingCollections.tsx, js/packages/web/src/ui/views/Home/Home.tsx
Home page list external collections
=> Collection list home page

js/packages/web/src/ui/sections/RecentCollections/RecentCollections.tsx, js/packages/web/src/ui/sections/TrendingCollections/TrendingCollections.tsx, js/packages/web/src/ui/views/Collection/Collection.tsx, js/packages/web/src/ui/views/Discover/Discover.tsx
Implemented External collection page.
=> External collection page 

js/packages/common/src/molecules/SectionHeading/SectionHeading.tsx, js/packages/web/src/hooks/useAttribute.ts, js/packages/web/src/ui/sections/NFTDetailsBody/NFTDetailsBody.tsx
=> Set attribute stats

js/packages/web/src/components/ArtCard/index.tsx, js/packages/web/src/views/artworks/components/ItemCard/index.tsx, js/packages/web/src/views/artworks/index.tsx
=> MY NFT ITEMS

js/packages/web/src/actions/createAuctionManager.ts, js/packages/web/src/components/ArtContent/index.tsx, js/packages/web/src/ui/sections/NFTDetailsBody/NFTDetailsBody.tsx, js/packages/web/src/ui/sections/NFTDetailsInfo/NFTDetailsInfo.tsx, js/packages/web/src/views/art/InstantSale.tsx, js/packages/web/src/views/art/PutOnAuction.tsx
- Set the current owner address to a detail page.
- Added auction time duration to put on auction.
=> Karmaplex bug fixes

js/packages/web/package.json, js/packages/web/src/api/launchpadSubmissionApi.ts, js/packages/web/src/components-v2/views/LaunchPadSubmission/LaunchPadSubmission.tsx, js/packages/web/src/routes.tsx, js/packages/web/src/ui/sections/CollectionSidebar/CollectionSidebar.tsx, js/packages/web/src/ui/sections/NFTDetailsInfo/NFTDetailsInfo.tsx, js/packages/web/src/ui/sections/NFTDetailsTopBar/NFTDetailsTopBar.tsx, js/packages/web/src/ui/views/Collection/Collection.tsx, js/packages/web/src/views/admin/index.tsx, js/yarn.lock
- [Add new route for update launchpad submission](https://github.com/rusiruavb/metaplex/commit/a9938ca546f205132a233f87d948176a9b816613)
- [Add new API endpoints to get collection header](https://github.com/rusiruavb/metaplex/commit/95dc8f763c4d5f3dd93e79a38a09e7ba1001b891)
- [Load previous values of the launchpad submission](https://github.com/rusiruavb/metaplex/commit/ad9d1bf7df538c5d5c5c5f7da28f550add9cf081)
- [Fix text copy paste issue in NFTDetails](https://github.com/rusiruavb/metaplex/commit/3152c2f47e191bf5f0b2e471900f6bbde3255326)
- [Add current endpoint to explore in solana link](https://github.com/rusiruavb/metaplex/commit/054b7e6c99e454d26b75575d9ec23a9649d49fbe)
- [Load collection header information from the submission](https://github.com/rusiruavb/metaplex/commit/850d86f06052 …
=> Bug fixes and update launchpad submission feature

js/packages/common/src/molecules/BidCard/BidCard.tsx, js/packages/web/src/ui/sections/Hero/Hero.tsx, js/packages/web/src/ui/sections/Hero/LiveNFTCard.tsx, js/packages/web/src/ui/sections/NFTDetailsTopBar/NFTDetailsTopBar.tsx, js/packages/web/src/ui/views/MyProfile/MyProfile.tsx
Bugs fixes.
- Display name of the Artist/Collection
- Remove "NFT's Minted", "Talented Artist" & "Daily SOL Volume"
- "Bid Now" Button should renamed as "View Collection"
- "Recent" should rename as "Recently Listed" and New filter as "Volume/Descending"  should added to Filter section
- Facilitate to navigate the Listed NFT's
=> Karma bug fixes

js/packages/common/src/molecules/BidCard/BidCard.tsx, js/packages/common/src/molecules/BuyCard/BuyCard.tsx, js/packages/web/src/ui/sections/Hero/LiveNFTCard.tsx, js/packages/web/src/ui/sections/NFTDetailsCurrentOffers/NFTDetailsCurrentOffers.tsx, js/packages/web/src/ui/sections/NFTDetailsTabs/NFTDetailsTabs.tsx, js/packages/web/src/ui/views/Discover/Discover.tsx
- Facilitate to search by Name and Other sorting options
- List Bid History
=> Discover collections search filters

js/packages/web/src/ui/views/Collection/Collection.tsx, js/packages/web/src/ui/views/Collection/useCollectionNft.ts
- Collection render issue fixed
=> Collection render issue fixed

js/packages/web/src/ui/sections/CollectionNftList/NFTCardWrapper.tsx, js/packages/web/src/ui/views/Collection/Collection.tsx, js/packages/web/src/ui/views/Collection/useCollectionNft.ts
Sort by Price low to high issue fixed
=> Sort-by-price

js/packages/web/src/api/tagApi.ts, js/packages/web/src/routes.tsx, js/packages/web/src/ui/views/Discover/Discover.tsx, js/yarn.lock
Search by tags in the discover page search.
Search by tags in main search
=> KARMAVERSE-87

js/packages/web/src/ui/sections/NFTDetailsCurrentOffers/NFTDetailsCurrentOffers.tsx, js/packages/web/src/views/home/setup.tsx
=> UI updates
